/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as PartnerPageRouteImport } from './routes/partner-page'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as AdminRecoveredRouteImport } from './routes/admin-recovered'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PolicyRouteImport } from './routes/Policy'
import { Route as LeadBucketDetailsRouteImport } from './routes/Lead-bucket-details'
import { Route as LeadBucketRouteImport } from './routes/Lead-bucket'
import { Route as LeadAssignmentRouteImport } from './routes/Lead-assignment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceLeadsIndexRouteImport } from './routes/service-Leads/index'
import { Route as UserSellingHistoryRouteImport } from './routes/user.selling-history'
import { Route as UserSellTabletRouteImport } from './routes/user.sell-tablet'
import { Route as UserSellPhoneRouteImport } from './routes/user.sell-phone'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserPickupStatusRouteImport } from './routes/user.pickup-status'
import { Route as UserPaymentsRouteImport } from './routes/user.payments'
import { Route as UserMyListingsRouteImport } from './routes/user.my-listings'
import { Route as UserLoginRouteImport } from './routes/user.login'
import { Route as UserListDeviceRouteImport } from './routes/user.list-device'
import { Route as ServiceLeadsTransactionRouteImport } from './routes/service-Leads/transaction'
import { Route as PartnerPageCoinsRouteImport } from './routes/partner-page.coins'
import { Route as LeadBucketUnlockPaymentRouteImport } from './routes/Lead-bucket.Unlock-payment'
import { Route as ServiceLeadsTransactionIndexRouteImport } from './routes/service-Leads/transaction/index'
import { Route as UserSellTabletQuoteRouteImport } from './routes/user.sell-tablet.quote'
import { Route as UserSellTabletDeviceDetailsRouteImport } from './routes/user.sell-tablet.device-details'
import { Route as UserSellPhoneQuoteRouteImport } from './routes/user.sell-phone.quote'
import { Route as UserSellPhoneDeviceDetailsRouteImport } from './routes/user.sell-phone.device-details'
import { Route as UserSellPhoneBrandRouteImport } from './routes/user.sell-phone.$brand'
import { Route as ServiceLeadsTransactionPaymentRouteImport } from './routes/service-Leads/transaction/payment'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPageRoute = PartnerPageRouteImport.update({
  id: '/partner-page',
  path: '/partner-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecoveredRoute = AdminRecoveredRouteImport.update({
  id: '/admin-recovered',
  path: '/admin-recovered',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/Policy',
  path: '/Policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadBucketDetailsRoute = LeadBucketDetailsRouteImport.update({
  id: '/Lead-bucket-details',
  path: '/Lead-bucket-details',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadBucketRoute = LeadBucketRouteImport.update({
  id: '/Lead-bucket',
  path: '/Lead-bucket',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadAssignmentRoute = LeadAssignmentRouteImport.update({
  id: '/Lead-assignment',
  path: '/Lead-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceLeadsIndexRoute = ServiceLeadsIndexRouteImport.update({
  id: '/service-Leads/',
  path: '/service-Leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSellingHistoryRoute = UserSellingHistoryRouteImport.update({
  id: '/selling-history',
  path: '/selling-history',
  getParentRoute: () => UserRoute,
} as any)
const UserSellTabletRoute = UserSellTabletRouteImport.update({
  id: '/sell-tablet',
  path: '/sell-tablet',
  getParentRoute: () => UserRoute,
} as any)
const UserSellPhoneRoute = UserSellPhoneRouteImport.update({
  id: '/sell-phone',
  path: '/sell-phone',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserPickupStatusRoute = UserPickupStatusRouteImport.update({
  id: '/pickup-status',
  path: '/pickup-status',
  getParentRoute: () => UserRoute,
} as any)
const UserPaymentsRoute = UserPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => UserRoute,
} as any)
const UserMyListingsRoute = UserMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => UserRoute,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UserRoute,
} as any)
const UserListDeviceRoute = UserListDeviceRouteImport.update({
  id: '/list-device',
  path: '/list-device',
  getParentRoute: () => UserRoute,
} as any)
const ServiceLeadsTransactionRoute = ServiceLeadsTransactionRouteImport.update({
  id: '/service-Leads/transaction',
  path: '/service-Leads/transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPageCoinsRoute = PartnerPageCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => PartnerPageRoute,
} as any)
const LeadBucketUnlockPaymentRoute = LeadBucketUnlockPaymentRouteImport.update({
  id: '/Unlock-payment',
  path: '/Unlock-payment',
  getParentRoute: () => LeadBucketRoute,
} as any)
const ServiceLeadsTransactionIndexRoute =
  ServiceLeadsTransactionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServiceLeadsTransactionRoute,
  } as any)
const UserSellTabletQuoteRoute = UserSellTabletQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => UserSellTabletRoute,
} as any)
const UserSellTabletDeviceDetailsRoute =
  UserSellTabletDeviceDetailsRouteImport.update({
    id: '/device-details',
    path: '/device-details',
    getParentRoute: () => UserSellTabletRoute,
  } as any)
const UserSellPhoneQuoteRoute = UserSellPhoneQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => UserSellPhoneRoute,
} as any)
const UserSellPhoneDeviceDetailsRoute =
  UserSellPhoneDeviceDetailsRouteImport.update({
    id: '/device-details',
    path: '/device-details',
    getParentRoute: () => UserSellPhoneRoute,
  } as any)
const UserSellPhoneBrandRoute = UserSellPhoneBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => UserSellPhoneRoute,
} as any)
const ServiceLeadsTransactionPaymentRoute =
  ServiceLeadsTransactionPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => ServiceLeadsTransactionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Lead-assignment': typeof LeadAssignmentRoute
  '/Lead-bucket': typeof LeadBucketRouteWithChildren
  '/Lead-bucket-details': typeof LeadBucketDetailsRoute
  '/Policy': typeof PolicyRoute
  '/admin': typeof AdminRoute
  '/admin-recovered': typeof AdminRecoveredRoute
  '/partner': typeof PartnerRoute
  '/partner-page': typeof PartnerPageRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/Lead-bucket/Unlock-payment': typeof LeadBucketUnlockPaymentRoute
  '/partner-page/coins': typeof PartnerPageCoinsRoute
  '/service-Leads/transaction': typeof ServiceLeadsTransactionRouteWithChildren
  '/user/list-device': typeof UserListDeviceRoute
  '/user/login': typeof UserLoginRoute
  '/user/my-listings': typeof UserMyListingsRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/pickup-status': typeof UserPickupStatusRoute
  '/user/profile': typeof UserProfileRoute
  '/user/sell-phone': typeof UserSellPhoneRouteWithChildren
  '/user/sell-tablet': typeof UserSellTabletRouteWithChildren
  '/user/selling-history': typeof UserSellingHistoryRoute
  '/service-Leads/': typeof ServiceLeadsIndexRoute
  '/service-Leads/transaction/payment': typeof ServiceLeadsTransactionPaymentRoute
  '/user/sell-phone/$brand': typeof UserSellPhoneBrandRoute
  '/user/sell-phone/device-details': typeof UserSellPhoneDeviceDetailsRoute
  '/user/sell-phone/quote': typeof UserSellPhoneQuoteRoute
  '/user/sell-tablet/device-details': typeof UserSellTabletDeviceDetailsRoute
  '/user/sell-tablet/quote': typeof UserSellTabletQuoteRoute
  '/service-Leads/transaction/': typeof ServiceLeadsTransactionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Lead-assignment': typeof LeadAssignmentRoute
  '/Lead-bucket': typeof LeadBucketRouteWithChildren
  '/Lead-bucket-details': typeof LeadBucketDetailsRoute
  '/Policy': typeof PolicyRoute
  '/admin': typeof AdminRoute
  '/admin-recovered': typeof AdminRecoveredRoute
  '/partner': typeof PartnerRoute
  '/partner-page': typeof PartnerPageRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/Lead-bucket/Unlock-payment': typeof LeadBucketUnlockPaymentRoute
  '/partner-page/coins': typeof PartnerPageCoinsRoute
  '/user/list-device': typeof UserListDeviceRoute
  '/user/login': typeof UserLoginRoute
  '/user/my-listings': typeof UserMyListingsRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/pickup-status': typeof UserPickupStatusRoute
  '/user/profile': typeof UserProfileRoute
  '/user/sell-phone': typeof UserSellPhoneRouteWithChildren
  '/user/sell-tablet': typeof UserSellTabletRouteWithChildren
  '/user/selling-history': typeof UserSellingHistoryRoute
  '/service-Leads': typeof ServiceLeadsIndexRoute
  '/service-Leads/transaction/payment': typeof ServiceLeadsTransactionPaymentRoute
  '/user/sell-phone/$brand': typeof UserSellPhoneBrandRoute
  '/user/sell-phone/device-details': typeof UserSellPhoneDeviceDetailsRoute
  '/user/sell-phone/quote': typeof UserSellPhoneQuoteRoute
  '/user/sell-tablet/device-details': typeof UserSellTabletDeviceDetailsRoute
  '/user/sell-tablet/quote': typeof UserSellTabletQuoteRoute
  '/service-Leads/transaction': typeof ServiceLeadsTransactionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Lead-assignment': typeof LeadAssignmentRoute
  '/Lead-bucket': typeof LeadBucketRouteWithChildren
  '/Lead-bucket-details': typeof LeadBucketDetailsRoute
  '/Policy': typeof PolicyRoute
  '/admin': typeof AdminRoute
  '/admin-recovered': typeof AdminRecoveredRoute
  '/partner': typeof PartnerRoute
  '/partner-page': typeof PartnerPageRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/Lead-bucket/Unlock-payment': typeof LeadBucketUnlockPaymentRoute
  '/partner-page/coins': typeof PartnerPageCoinsRoute
  '/service-Leads/transaction': typeof ServiceLeadsTransactionRouteWithChildren
  '/user/list-device': typeof UserListDeviceRoute
  '/user/login': typeof UserLoginRoute
  '/user/my-listings': typeof UserMyListingsRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/pickup-status': typeof UserPickupStatusRoute
  '/user/profile': typeof UserProfileRoute
  '/user/sell-phone': typeof UserSellPhoneRouteWithChildren
  '/user/sell-tablet': typeof UserSellTabletRouteWithChildren
  '/user/selling-history': typeof UserSellingHistoryRoute
  '/service-Leads/': typeof ServiceLeadsIndexRoute
  '/service-Leads/transaction/payment': typeof ServiceLeadsTransactionPaymentRoute
  '/user/sell-phone/$brand': typeof UserSellPhoneBrandRoute
  '/user/sell-phone/device-details': typeof UserSellPhoneDeviceDetailsRoute
  '/user/sell-phone/quote': typeof UserSellPhoneQuoteRoute
  '/user/sell-tablet/device-details': typeof UserSellTabletDeviceDetailsRoute
  '/user/sell-tablet/quote': typeof UserSellTabletQuoteRoute
  '/service-Leads/transaction/': typeof ServiceLeadsTransactionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Lead-assignment'
    | '/Lead-bucket'
    | '/Lead-bucket-details'
    | '/Policy'
    | '/admin'
    | '/admin-recovered'
    | '/partner'
    | '/partner-page'
    | '/user'
    | '/Lead-bucket/Unlock-payment'
    | '/partner-page/coins'
    | '/service-Leads/transaction'
    | '/user/list-device'
    | '/user/login'
    | '/user/my-listings'
    | '/user/payments'
    | '/user/pickup-status'
    | '/user/profile'
    | '/user/sell-phone'
    | '/user/sell-tablet'
    | '/user/selling-history'
    | '/service-Leads/'
    | '/service-Leads/transaction/payment'
    | '/user/sell-phone/$brand'
    | '/user/sell-phone/device-details'
    | '/user/sell-phone/quote'
    | '/user/sell-tablet/device-details'
    | '/user/sell-tablet/quote'
    | '/service-Leads/transaction/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Lead-assignment'
    | '/Lead-bucket'
    | '/Lead-bucket-details'
    | '/Policy'
    | '/admin'
    | '/admin-recovered'
    | '/partner'
    | '/partner-page'
    | '/user'
    | '/Lead-bucket/Unlock-payment'
    | '/partner-page/coins'
    | '/user/list-device'
    | '/user/login'
    | '/user/my-listings'
    | '/user/payments'
    | '/user/pickup-status'
    | '/user/profile'
    | '/user/sell-phone'
    | '/user/sell-tablet'
    | '/user/selling-history'
    | '/service-Leads'
    | '/service-Leads/transaction/payment'
    | '/user/sell-phone/$brand'
    | '/user/sell-phone/device-details'
    | '/user/sell-phone/quote'
    | '/user/sell-tablet/device-details'
    | '/user/sell-tablet/quote'
    | '/service-Leads/transaction'
  id:
    | '__root__'
    | '/'
    | '/Lead-assignment'
    | '/Lead-bucket'
    | '/Lead-bucket-details'
    | '/Policy'
    | '/admin'
    | '/admin-recovered'
    | '/partner'
    | '/partner-page'
    | '/user'
    | '/Lead-bucket/Unlock-payment'
    | '/partner-page/coins'
    | '/service-Leads/transaction'
    | '/user/list-device'
    | '/user/login'
    | '/user/my-listings'
    | '/user/payments'
    | '/user/pickup-status'
    | '/user/profile'
    | '/user/sell-phone'
    | '/user/sell-tablet'
    | '/user/selling-history'
    | '/service-Leads/'
    | '/service-Leads/transaction/payment'
    | '/user/sell-phone/$brand'
    | '/user/sell-phone/device-details'
    | '/user/sell-phone/quote'
    | '/user/sell-tablet/device-details'
    | '/user/sell-tablet/quote'
    | '/service-Leads/transaction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadAssignmentRoute: typeof LeadAssignmentRoute
  LeadBucketRoute: typeof LeadBucketRouteWithChildren
  LeadBucketDetailsRoute: typeof LeadBucketDetailsRoute
  PolicyRoute: typeof PolicyRoute
  AdminRoute: typeof AdminRoute
  AdminRecoveredRoute: typeof AdminRecoveredRoute
  PartnerRoute: typeof PartnerRoute
  PartnerPageRoute: typeof PartnerPageRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  ServiceLeadsTransactionRoute: typeof ServiceLeadsTransactionRouteWithChildren
  ServiceLeadsIndexRoute: typeof ServiceLeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-page': {
      id: '/partner-page'
      path: '/partner-page'
      fullPath: '/partner-page'
      preLoaderRoute: typeof PartnerPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-recovered': {
      id: '/admin-recovered'
      path: '/admin-recovered'
      fullPath: '/admin-recovered'
      preLoaderRoute: typeof AdminRecoveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Policy': {
      id: '/Policy'
      path: '/Policy'
      fullPath: '/Policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Lead-bucket-details': {
      id: '/Lead-bucket-details'
      path: '/Lead-bucket-details'
      fullPath: '/Lead-bucket-details'
      preLoaderRoute: typeof LeadBucketDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Lead-bucket': {
      id: '/Lead-bucket'
      path: '/Lead-bucket'
      fullPath: '/Lead-bucket'
      preLoaderRoute: typeof LeadBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Lead-assignment': {
      id: '/Lead-assignment'
      path: '/Lead-assignment'
      fullPath: '/Lead-assignment'
      preLoaderRoute: typeof LeadAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-Leads/': {
      id: '/service-Leads/'
      path: '/service-Leads'
      fullPath: '/service-Leads/'
      preLoaderRoute: typeof ServiceLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/selling-history': {
      id: '/user/selling-history'
      path: '/selling-history'
      fullPath: '/user/selling-history'
      preLoaderRoute: typeof UserSellingHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/sell-tablet': {
      id: '/user/sell-tablet'
      path: '/sell-tablet'
      fullPath: '/user/sell-tablet'
      preLoaderRoute: typeof UserSellTabletRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/sell-phone': {
      id: '/user/sell-phone'
      path: '/sell-phone'
      fullPath: '/user/sell-phone'
      preLoaderRoute: typeof UserSellPhoneRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/pickup-status': {
      id: '/user/pickup-status'
      path: '/pickup-status'
      fullPath: '/user/pickup-status'
      preLoaderRoute: typeof UserPickupStatusRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/payments': {
      id: '/user/payments'
      path: '/payments'
      fullPath: '/user/payments'
      preLoaderRoute: typeof UserPaymentsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/my-listings': {
      id: '/user/my-listings'
      path: '/my-listings'
      fullPath: '/user/my-listings'
      preLoaderRoute: typeof UserMyListingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/login': {
      id: '/user/login'
      path: '/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/list-device': {
      id: '/user/list-device'
      path: '/list-device'
      fullPath: '/user/list-device'
      preLoaderRoute: typeof UserListDeviceRouteImport
      parentRoute: typeof UserRoute
    }
    '/service-Leads/transaction': {
      id: '/service-Leads/transaction'
      path: '/service-Leads/transaction'
      fullPath: '/service-Leads/transaction'
      preLoaderRoute: typeof ServiceLeadsTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-page/coins': {
      id: '/partner-page/coins'
      path: '/coins'
      fullPath: '/partner-page/coins'
      preLoaderRoute: typeof PartnerPageCoinsRouteImport
      parentRoute: typeof PartnerPageRoute
    }
    '/Lead-bucket/Unlock-payment': {
      id: '/Lead-bucket/Unlock-payment'
      path: '/Unlock-payment'
      fullPath: '/Lead-bucket/Unlock-payment'
      preLoaderRoute: typeof LeadBucketUnlockPaymentRouteImport
      parentRoute: typeof LeadBucketRoute
    }
    '/service-Leads/transaction/': {
      id: '/service-Leads/transaction/'
      path: '/'
      fullPath: '/service-Leads/transaction/'
      preLoaderRoute: typeof ServiceLeadsTransactionIndexRouteImport
      parentRoute: typeof ServiceLeadsTransactionRoute
    }
    '/user/sell-tablet/quote': {
      id: '/user/sell-tablet/quote'
      path: '/quote'
      fullPath: '/user/sell-tablet/quote'
      preLoaderRoute: typeof UserSellTabletQuoteRouteImport
      parentRoute: typeof UserSellTabletRoute
    }
    '/user/sell-tablet/device-details': {
      id: '/user/sell-tablet/device-details'
      path: '/device-details'
      fullPath: '/user/sell-tablet/device-details'
      preLoaderRoute: typeof UserSellTabletDeviceDetailsRouteImport
      parentRoute: typeof UserSellTabletRoute
    }
    '/user/sell-phone/quote': {
      id: '/user/sell-phone/quote'
      path: '/quote'
      fullPath: '/user/sell-phone/quote'
      preLoaderRoute: typeof UserSellPhoneQuoteRouteImport
      parentRoute: typeof UserSellPhoneRoute
    }
    '/user/sell-phone/device-details': {
      id: '/user/sell-phone/device-details'
      path: '/device-details'
      fullPath: '/user/sell-phone/device-details'
      preLoaderRoute: typeof UserSellPhoneDeviceDetailsRouteImport
      parentRoute: typeof UserSellPhoneRoute
    }
    '/user/sell-phone/$brand': {
      id: '/user/sell-phone/$brand'
      path: '/$brand'
      fullPath: '/user/sell-phone/$brand'
      preLoaderRoute: typeof UserSellPhoneBrandRouteImport
      parentRoute: typeof UserSellPhoneRoute
    }
    '/service-Leads/transaction/payment': {
      id: '/service-Leads/transaction/payment'
      path: '/payment'
      fullPath: '/service-Leads/transaction/payment'
      preLoaderRoute: typeof ServiceLeadsTransactionPaymentRouteImport
      parentRoute: typeof ServiceLeadsTransactionRoute
    }
  }
}

interface LeadBucketRouteChildren {
  LeadBucketUnlockPaymentRoute: typeof LeadBucketUnlockPaymentRoute
}

const LeadBucketRouteChildren: LeadBucketRouteChildren = {
  LeadBucketUnlockPaymentRoute: LeadBucketUnlockPaymentRoute,
}

const LeadBucketRouteWithChildren = LeadBucketRoute._addFileChildren(
  LeadBucketRouteChildren,
)

interface PartnerPageRouteChildren {
  PartnerPageCoinsRoute: typeof PartnerPageCoinsRoute
}

const PartnerPageRouteChildren: PartnerPageRouteChildren = {
  PartnerPageCoinsRoute: PartnerPageCoinsRoute,
}

const PartnerPageRouteWithChildren = PartnerPageRoute._addFileChildren(
  PartnerPageRouteChildren,
)

interface UserSellPhoneRouteChildren {
  UserSellPhoneBrandRoute: typeof UserSellPhoneBrandRoute
  UserSellPhoneDeviceDetailsRoute: typeof UserSellPhoneDeviceDetailsRoute
  UserSellPhoneQuoteRoute: typeof UserSellPhoneQuoteRoute
}

const UserSellPhoneRouteChildren: UserSellPhoneRouteChildren = {
  UserSellPhoneBrandRoute: UserSellPhoneBrandRoute,
  UserSellPhoneDeviceDetailsRoute: UserSellPhoneDeviceDetailsRoute,
  UserSellPhoneQuoteRoute: UserSellPhoneQuoteRoute,
}

const UserSellPhoneRouteWithChildren = UserSellPhoneRoute._addFileChildren(
  UserSellPhoneRouteChildren,
)

interface UserSellTabletRouteChildren {
  UserSellTabletDeviceDetailsRoute: typeof UserSellTabletDeviceDetailsRoute
  UserSellTabletQuoteRoute: typeof UserSellTabletQuoteRoute
}

const UserSellTabletRouteChildren: UserSellTabletRouteChildren = {
  UserSellTabletDeviceDetailsRoute: UserSellTabletDeviceDetailsRoute,
  UserSellTabletQuoteRoute: UserSellTabletQuoteRoute,
}

const UserSellTabletRouteWithChildren = UserSellTabletRoute._addFileChildren(
  UserSellTabletRouteChildren,
)

interface UserRouteChildren {
  UserListDeviceRoute: typeof UserListDeviceRoute
  UserLoginRoute: typeof UserLoginRoute
  UserMyListingsRoute: typeof UserMyListingsRoute
  UserPaymentsRoute: typeof UserPaymentsRoute
  UserPickupStatusRoute: typeof UserPickupStatusRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSellPhoneRoute: typeof UserSellPhoneRouteWithChildren
  UserSellTabletRoute: typeof UserSellTabletRouteWithChildren
  UserSellingHistoryRoute: typeof UserSellingHistoryRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserListDeviceRoute: UserListDeviceRoute,
  UserLoginRoute: UserLoginRoute,
  UserMyListingsRoute: UserMyListingsRoute,
  UserPaymentsRoute: UserPaymentsRoute,
  UserPickupStatusRoute: UserPickupStatusRoute,
  UserProfileRoute: UserProfileRoute,
  UserSellPhoneRoute: UserSellPhoneRouteWithChildren,
  UserSellTabletRoute: UserSellTabletRouteWithChildren,
  UserSellingHistoryRoute: UserSellingHistoryRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface ServiceLeadsTransactionRouteChildren {
  ServiceLeadsTransactionPaymentRoute: typeof ServiceLeadsTransactionPaymentRoute
  ServiceLeadsTransactionIndexRoute: typeof ServiceLeadsTransactionIndexRoute
}

const ServiceLeadsTransactionRouteChildren: ServiceLeadsTransactionRouteChildren =
  {
    ServiceLeadsTransactionPaymentRoute: ServiceLeadsTransactionPaymentRoute,
    ServiceLeadsTransactionIndexRoute: ServiceLeadsTransactionIndexRoute,
  }

const ServiceLeadsTransactionRouteWithChildren =
  ServiceLeadsTransactionRoute._addFileChildren(
    ServiceLeadsTransactionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadAssignmentRoute: LeadAssignmentRoute,
  LeadBucketRoute: LeadBucketRouteWithChildren,
  LeadBucketDetailsRoute: LeadBucketDetailsRoute,
  PolicyRoute: PolicyRoute,
  AdminRoute: AdminRoute,
  AdminRecoveredRoute: AdminRecoveredRoute,
  PartnerRoute: PartnerRoute,
  PartnerPageRoute: PartnerPageRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  ServiceLeadsTransactionRoute: ServiceLeadsTransactionRouteWithChildren,
  ServiceLeadsIndexRoute: ServiceLeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
